#!/usr/bin/env bash
set -euo pipefail

# ===========================================
# OpenClaw Sync Script (Reverse GitOps)
# Reads live config, strips secrets,
# updates template + skills list in repo.
# ===========================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OPENCLAW_HOME="$HOME/.openclaw"
LIVE_CONFIG="$OPENCLAW_HOME/openclaw.json"
TEMPLATE="$PROJECT_DIR/openclaw.template.json"
SKILLS_LIST="$PROJECT_DIR/skills/skills-list.md"
SKILLS_DIR="$OPENCLAW_HOME/skills"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

echo "=========================================="
echo " OpenClaw Sync (Reverse GitOps)"
if $DRY_RUN; then
  echo " [DRY RUN — no files will be modified]"
fi
echo "=========================================="
echo ""

# --- Pre-flight ---
if [ ! -f "$LIVE_CONFIG" ]; then
  echo "ERROR: Live config not found: $LIVE_CONFIG"
  echo "Run 'openclaw onboard --install-daemon' first."
  exit 1
fi

if [ ! -f "$TEMPLATE" ]; then
  echo "ERROR: Template not found: $TEMPLATE"
  exit 1
fi

if ! command -v node &>/dev/null; then
  echo "ERROR: Node.js required for JSON processing."
  exit 1
fi

# --- Sync config ---
echo "[1/2] Syncing live config → template..."

SYNC_RESULT=$(node -e "
const fs = require('fs');

const live = JSON.parse(fs.readFileSync('$LIVE_CONFIG', 'utf8'));
const template = JSON.parse(fs.readFileSync('$TEMPLATE', 'utf8'));

// Build sanitized config from live, stripping secrets and internal fields
const sanitized = JSON.parse(JSON.stringify(live));

// Remove secrets: gateway token
if (sanitized.gateway?.auth?.token) {
  delete sanitized.gateway.auth.token;
  sanitized.gateway.auth._token_comment = 'Token is auto-generated by onboard wizard. Do NOT put real token here.';
}

// Remove secrets: telegram bot token (single-account legacy)
if (sanitized.channels?.telegram?.botToken) {
  delete sanitized.channels.telegram.botToken;
  sanitized.channels.telegram._botToken_comment = 'Set via OPENCLAW_TELEGRAM_BOT_TOKEN env var or paste during onboard wizard';
}

// Remove secrets: telegram account tokens (multi-account)
if (sanitized.channels?.telegram?.accounts) {
  for (const [name, acct] of Object.entries(sanitized.channels.telegram.accounts)) {
    if (acct.botToken) {
      delete acct.botToken;
      acct._botToken_comment = 'Set via env var';
    }
  }
}

// Remove secrets: auth profile keys/tokens
if (sanitized.auth?.profiles) {
  for (const key of Object.keys(sanitized.auth.profiles)) {
    const p = sanitized.auth.profiles[key];
    delete p.apiKey;
    delete p.token;
  }
}

// Remove internal fields
delete sanitized.meta;
delete sanitized.wizard;

// Add schema and comment from original template
const result = { '\$schema': template['\$schema'] || 'https://docs.openclaw.ai/schema/openclaw.json' };
result._comment = template._comment || 'OpenClaw config template. Secrets (tokens, API keys) should use env vars, not this file.';

// Merge remaining keys in a stable order: follow template key order first, then any new keys from live
const templateKeys = Object.keys(template).filter(k => k !== '\$schema' && k !== '_comment');
const sanitizedKeys = Object.keys(sanitized).filter(k => k !== '\$schema' && k !== '_comment');
const allKeys = [...new Set([...templateKeys, ...sanitizedKeys])];

for (const key of allKeys) {
  if (sanitized[key] !== undefined) {
    result[key] = sanitized[key];
  }
}

const newJson = JSON.stringify(result, null, 2) + '\n';
const oldJson = fs.readFileSync('$TEMPLATE', 'utf8');

if (newJson === oldJson) {
  console.log(JSON.stringify({ changed: false, diff: null }));
} else {
  console.log(JSON.stringify({ changed: true, diff: 'template updated' }));
  if ('$DRY_RUN' !== 'true') {
    fs.writeFileSync('$TEMPLATE', newJson);
  }
}
")

CONFIG_CHANGED=$(echo "$SYNC_RESULT" | node -e "const d=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')); console.log(d.changed)")

if [ "$CONFIG_CHANGED" = "true" ]; then
  echo "  Template has changes."
  if $DRY_RUN; then
    echo "  [dry-run] Would update: $TEMPLATE"
    echo ""
    echo "  Preview diff:"
    # Generate preview to temp file and diff
    node -e "
    const fs = require('fs');
    const live = JSON.parse(fs.readFileSync('$LIVE_CONFIG', 'utf8'));
    const template = JSON.parse(fs.readFileSync('$TEMPLATE', 'utf8'));

    const sanitized = JSON.parse(JSON.stringify(live));

    if (sanitized.gateway?.auth?.token) {
      delete sanitized.gateway.auth.token;
      sanitized.gateway.auth._token_comment = 'Token is auto-generated by onboard wizard. Do NOT put real token here.';
    }
    if (sanitized.channels?.telegram?.botToken) {
      delete sanitized.channels.telegram.botToken;
      sanitized.channels.telegram._botToken_comment = 'Set via OPENCLAW_TELEGRAM_BOT_TOKEN env var or paste during onboard wizard';
    }
    if (sanitized.channels?.telegram?.accounts) {
      for (const [name, acct] of Object.entries(sanitized.channels.telegram.accounts)) {
        if (acct.botToken) {
          delete acct.botToken;
          acct._botToken_comment = 'Set via env var';
        }
      }
    }
    if (sanitized.auth?.profiles) {
      for (const key of Object.keys(sanitized.auth.profiles)) {
        delete sanitized.auth.profiles[key].apiKey;
        delete sanitized.auth.profiles[key].token;
      }
    }
    delete sanitized.meta;
    delete sanitized.wizard;

    const result = { '\$schema': template['\$schema'] || 'https://docs.openclaw.ai/schema/openclaw.json' };
    result._comment = template._comment || 'OpenClaw config template. Secrets (tokens, API keys) should use env vars, not this file.';
    const templateKeys = Object.keys(template).filter(k => k !== '\$schema' && k !== '_comment');
    const sanitizedKeys = Object.keys(sanitized).filter(k => k !== '\$schema' && k !== '_comment');
    const allKeys = [...new Set([...templateKeys, ...sanitizedKeys])];
    for (const key of allKeys) {
      if (sanitized[key] !== undefined) result[key] = sanitized[key];
    }

    fs.writeFileSync('/tmp/openclaw-sync-preview.$$.json', JSON.stringify(result, null, 2) + '\n');
    "
    diff "$TEMPLATE" "/tmp/openclaw-sync-preview.$$.json" || true
    rm -f "/tmp/openclaw-sync-preview.$$.json"
  fi
else
  echo "  No config changes detected."
fi

# --- Sync skills ---
echo ""
echo "[2/2] Syncing installed skills..."

SKILLS_ADDED=()
SKILLS_REMOVED=()

if [ -d "$SKILLS_DIR" ]; then
  # Get currently installed skills
  INSTALLED_SKILLS=()
  if [ "$(ls -A "$SKILLS_DIR" 2>/dev/null)" ]; then
    while IFS= read -r skill; do
      INSTALLED_SKILLS+=("$skill")
    done < <(ls -1 "$SKILLS_DIR")
  fi

  # Get skills listed in skills-list.md (parse table rows)
  LISTED_SKILLS=()
  if [ -f "$SKILLS_LIST" ]; then
    while IFS= read -r skill; do
      LISTED_SKILLS+=("$skill")
    done < <(node -e "
      const fs = require('fs');
      const content = fs.readFileSync('$SKILLS_LIST', 'utf8');
      // Only match skills installed to ~/.openclaw/skills (not npm global ones)
      const lines = content.split('\\n');
      const skills = new Set();
      for (const line of lines) {
        const m = line.match(/^\| ([\w][\w.-]*) \|/);
        if (m && m[1] !== 'Skill' && line.includes('.openclaw/skills')) {
          skills.add(m[1]);
        }
      }
      for (const s of skills) console.log(s);
    ")
  fi

  # Find new skills (installed but not listed)
  for skill in "${INSTALLED_SKILLS[@]:-}"; do
    [ -z "$skill" ] && continue
    found=false
    for listed in "${LISTED_SKILLS[@]:-}"; do
      [ -z "$listed" ] && continue
      if [ "$skill" = "$listed" ]; then
        found=true
        break
      fi
    done
    if ! $found; then
      SKILLS_ADDED+=("$skill")
    fi
  done

  # Find removed skills (listed but not installed)
  for listed in "${LISTED_SKILLS[@]:-}"; do
    [ -z "$listed" ] && continue
    found=false
    for skill in "${INSTALLED_SKILLS[@]:-}"; do
      [ -z "$skill" ] && continue
      if [ "$listed" = "$skill" ]; then
        found=true
        break
      fi
    done
    if ! $found; then
      SKILLS_REMOVED+=("$listed")
    fi
  done

  if [ ${#SKILLS_ADDED[@]} -gt 0 ]; then
    echo "  New skills detected: ${SKILLS_ADDED[*]}"
    if ! $DRY_RUN && [ -f "$SKILLS_LIST" ]; then
      # Append to skills-list.md under "Recently Installed" section
      {
        echo ""
        echo "## Recently Installed (auto-detected by sync.sh)"
        echo ""
        echo "| Skill | Install Command | Purpose |"
        echo "|-------|----------------|---------|"
        for skill in "${SKILLS_ADDED[@]}"; do
          echo "| $skill | \`openclaw skill install $skill\` | (auto-detected — update purpose manually) |"
        done
      } >> "$SKILLS_LIST"
      echo "  Updated: $SKILLS_LIST"
    elif $DRY_RUN; then
      echo "  [dry-run] Would append to: $SKILLS_LIST"
    fi
  fi

  if [ ${#SKILLS_REMOVED[@]} -gt 0 ]; then
    echo "  Removed skills detected: ${SKILLS_REMOVED[*]}"
    echo "  NOTE: Please manually remove these from $SKILLS_LIST"
  fi

  if [ ${#SKILLS_ADDED[@]} -eq 0 ] && [ ${#SKILLS_REMOVED[@]} -eq 0 ]; then
    echo "  No skill changes detected."
  fi
else
  echo "  Skills directory not found: $SKILLS_DIR"
fi

echo ""
echo "=========================================="
echo " Sync complete."
echo "=========================================="

if $DRY_RUN; then
  echo ""
  echo "This was a dry run. No files were modified."
  echo "Run without --dry-run to apply changes."
else
  echo ""
  if [ "$CONFIG_CHANGED" = "true" ] || [ ${#SKILLS_ADDED[@]} -gt 0 ]; then
    echo "Files updated. Review with: git diff"
    echo "Then commit with a conventional commit message."
  else
    echo "No changes to sync."
  fi
fi
